version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ProjectName=cf-templates
      - S3Bucket=codebuild-nested-templates
  build:
    commands:
      - echo package CFN template
      - aws cloudformation package --template-file $ProjectName/main.yaml --s3-bucket $S3Bucket --output-template-file $ProjectName/main-updated.yaml
  post_build:
    commands:
      - echo upload template to S3 completed
artifacts:
  files:
    - $ProjectName/main-updated.yaml
  discard-paths: yes
