version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo package CFN template
      - aws cloudformation package --template-file /Users/hangpham/aws-training/cf-templates/dynamodb-tables.yaml --s3-bucket sample-templates --s3-prefix codebuild --output-template-file dynamodb-tables.yaml
      - aws cloudformation package --template-file /Users/hangpham/aws-training/cf-templates/product-delivery-apis.yaml --s3-bucket sample-templates --s3-prefix codebuild --output-template-file product-delivery-apis.yaml
      - aws cloudformation package --template-file /Users/hangpham/aws-training/cf-templates/lambda-sns-send-message.yaml --s3-bucket sample-templates --s3-prefix codebuild --output-template-file lambda-sns-send-message.yaml
  post_build:
    commands:
      - echo upload template to S3