version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ProjectName=cf-templates
      - S3Bucket=codebuild-sample-templates
  build:
    commands:
      - echo package CFN template
      - aws cloudformation package --template-file $ProjectName/main.yaml --s3-bucket $S3Bucket --s3-prefix codebuild --output-template-file $ProjectName/main.yaml
  post_build:
    commands:
      - echo upload template to S3