AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stacks for my sample app

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Dynamodb
      Parameters:
      - ProductTable
      - OrderTable
    - Label:
        default: Cognito
      Parameters:
      - CognitoDomain
      - CallbackURL
      - IdentityPoolName
    - Label:
        default: APIGateway
      Parameters:
      - APIName
      - APIGatewayType
    - Label:
        default: SNS
      Parameters:
      - AdminEmail
      - TopicName
Parameters:
  ProductTable:
    Type: String
  OrderTable:
    Type: String
  CognitoDomain:
    Type: String
    AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$
    Description: Enter a Cognito domain name. Must be alpha numeric 3-63 in length.
  CallbackURL:
    Type: String
  IdentityPoolName:
    Type: String
  APIName:
    Type: String
  APIGatewayType:
    Type: String
  AdminEmail:
    Type: String
    Description: Enter an admin's email.
  TopicName:
    Type: String
Resources:
  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackName:
          Ref: AWS::StackName
        ProductTable:
          Ref: ProductTable
        OrderTable:
          Ref: OrderTable
        AdminEmail:
          Ref: AdminEmail
        TopicName:
          Ref: TopicName
      TemplateURL: ./cf-templates/dynamodb-tables.yaml
  Apis:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - Database
    Properties:
      Parameters:
        StackName:
          Ref: AWS::StackName
        APIName:
          Ref: APIName
        APIGatewayType:
          Ref: APIGatewayType
        CognitoDomain:
          Ref: CognitoDomain
        CallbackURL:
          Ref: CallbackURL
        IdentityPoolName:
          Ref: IdentityPoolName
      TemplateURL: ./cf-templates/product-delivery-apis.yaml
