AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Lambda Function add product item to DynamoDB table.
Resources:
  # Define lambda execution role
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyName: LambdaPolicyProduct
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'
                Effect: Allow
              - Action:
                - 'dynamodb:PutItem'
                - 'dynamodb:BatchGetItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:BatchWriteItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                Resource:
                  - 'arn:aws:dynamodb:us-west-2:376387039631:table/Product'
                Effect: Allow

      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  # Define create product lambda function
  CreateProductItemFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: create-product
      Description: Lambda Function to create product item to DynamoDB
      Runtime: python3.8
      Code:
        S3Bucket: create-product-function
        S3Key: 92ee1584456d4339e71652216a1a6b88
      Handler: lambda-functions/create-product.handler
      MemorySize: 128
      Timeout: 10
      Role:
        !GetAtt LambdaExecutionRole.Arn